backend:
  name: github
  repo: nareshvnit/website_repo
  branch: main
  auth_type: implicit
  app_id: Ov23lirVgQLHFhEyqREV
  base_url: https://github.com

site_url: https://nareshvnit.github.io/website_repo
display_url: https://nareshvnit.github.io/website_repo

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Experience"
        name: "experience"
        file: "content/experience/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
